version: 2.0.3-alpha{build}
branches:
  only:
  - master
  - develop
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_user: dd4t
  nuget_password:
    secure: jddDaP9QBeCKjtrNE//jlw==
install:
- nuget sources add -Name Incentro -Source http://developer.incentro.com/nexus/service/local/nuget/tridion.net/ -UserName %nuget_user% -Password %nuget_password%
- choco install msbuild.communitytasks -y
- choco install ilmerge -y
build:
  project: build.msbuild
  verbosity: normal
artifacts:
- path: build/package/**/*.zip
  name: Package
deploy:
- provider: GitHub
  tag: v{appveyor_build_version}
  auth_token:
    secure: UfVipK2YzugPd54B3ls2zFwGuZVeMTH9cXwP22V9RVO/AACEjvROyFGspb1/ljwm
  artifact: '*.zip'
  on:
    branch: master