version: 2.0.3-alpha{build}
branches:
  only:
  - master
  - develop
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_user: dd4t
  nuget_password:
    secure: fcubeaS+/aDXFPSjbqgrQg==
install:
- choco install msbuild.communitytasks -y
- choco install ilmerge -y
- nuget sources add -Name Incentro -Source http://developer.incentro.com/nexus/service/local/nuget/tridion.net/ -UserName %nuget_user% -Password %nuget_password% 
build:
  project: build.msbuild
  verbosity: normal
artifacts:
- path: build/package/**/*.zip
  name: Zip package